# Shell variables
# Generated by 'wal'
wallpaper='/home/shaked/Pictures/230_-_brwKM4W.png'

# Special
background='#27221e'
foreground='#9ecfdc'
cursor='#9ecfdc'

# Colors
color0='#27221e'
color1='#03718C'
color2='#5D7A85'
color3='#0F94A8'
color4='#609DA9'
color5='#02ACCF'
color6='#34AECA'
color7='#9ecfdc'
color8='#6e909a'
color9='#03718C'
color10='#5D7A85'
color11='#0F94A8'
color12='#609DA9'
color13='#02ACCF'
color14='#34AECA'
color15='#9ecfdc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
